// Mock Product Data with proper placeholder images
export const products = [
  {
    id: 1,
    name: "Pro Wireless Earbuds X1",
    description:
      "Premium wireless earbuds with active noise cancellation, 30-hour battery life, and crystal-clear audio. Perfect for music lovers and professionals.",
    price: 299.99,
    originalPrice: 349.99,
    images: [
      "/premium-black-wireless-earbuds-modern-design-produ.jpg",
      "/wireless-earbuds-in-charging-case-white-background.jpg",
      "/person-wearing-wireless-earbuds-lifestyle-photo.jpg",
      "/earbuds-product-packaging-premium.jpg",
    ],
    category: "earbuds",
    brand: "TECH STORE",
    features: ["Active Noise Cancellation", "30hr Battery", "Wireless Charging", "IPX5 Water Resistant"],
    variants: {
      colors: ["Midnight Black", "Pearl White", "Space Gray"],
    },
    stock: 50,
    rating: 4.8,
    reviews: 1247,
    isNew: true,
  },
  {
    id: 2,
    name: "Ultra Smart Watch Pro",
    description:
      "Advanced smartwatch with health monitoring, GPS tracking, and seamless connectivity. Your perfect fitness and lifestyle companion.",
    price: 449.99,
    originalPrice: 499.99,
    images: [
      "/premium-black-smartwatch-modern-sleek-design-produ.jpg",
      "/smartwatch-on-wrist-fitness-tracking-lifestyle.jpg",
      "/smartwatch-display-showing-health-metrics.jpg",
      "/smartwatch-charging-dock-premium.jpg",
    ],
    category: "watches",
    brand: "TECH STORE",
    features: ["Health Monitoring", "GPS Tracking", "5-Day Battery", "Always-On Display"],
    variants: {
      colors: ["Obsidian", "Silver Titanium", "Rose Gold"],
      sizes: ["41mm", "45mm"],
    },
    stock: 35,
    rating: 4.9,
    reviews: 892,
    isNew: false,
  },
  {
    id: 3,
    name: "Power Station Elite",
    description:
      "High-capacity portable charger with fast charging technology. Power all your devices on the go with style.",
    price: 129.99,
    originalPrice: 149.99,
    images: [
      "/premium-black-portable-power-bank-modern-minimal-d.jpg",
      "/power-bank-charging-smartphone-lifestyle.jpg",
      "/sleek-power-bank-in-hand-premium-tech.jpg",
      "/power-bank-led-display-charging.jpg",
    ],
    category: "accessories",
    brand: "TECH STORE",
    features: ["20000mAh Capacity", "65W Fast Charging", "USB-C PD", "LED Display"],
    variants: {
      colors: ["Graphite", "Arctic White"],
    },
    stock: 100,
    rating: 4.7,
    reviews: 2156,
    isNew: false,
  },
  {
    id: 4,
    name: "Studio Headphones Max",
    description:
      "Studio-quality over-ear headphones with premium comfort and exceptional sound. Experience music like never before.",
    price: 379.99,
    originalPrice: 429.99,
    images: [
      "/premium-over-ear-headphones-black-luxury-design-pr.jpg",
      "/headphones-folded-compact-premium.jpg",
      "/person-wearing-premium-headphones-urban-lifestyle.jpg",
      "/headphones-detail-cushion-leather-premium.jpg",
    ],
    category: "headphones",
    brand: "TECH STORE",
    features: ["40mm Drivers", "ANC Technology", "40hr Battery", "Premium Leather"],
    variants: {
      colors: ["Matte Black", "Cream White", "Navy Blue"],
    },
    stock: 45,
    rating: 4.9,
    reviews: 1834,
    isNew: true,
  },
  {
    id: 5,
    name: "4K Webcam Pro",
    description:
      "Professional-grade webcam with 4K resolution and AI-powered auto-framing. Perfect for meetings and content creation.",
    price: 199.99,
    originalPrice: 249.99,
    images: [
      "/premium-4k-webcam-black-modern-design-product.jpg",
      "/webcam-on-monitor-desk-setup.jpg",
      "/webcam-streaming-content-creator-setup.jpg",
      "/webcam-product-side-angle.jpg",
    ],
    category: "gadgets",
    brand: "TECH STORE",
    features: ["4K Resolution", "AI Auto-Frame", "Dual Microphones", "Low Light Correction"],
    variants: {
      colors: ["Black"],
    },
    stock: 60,
    rating: 4.6,
    reviews: 567,
    isNew: false,
  },
  {
    id: 6,
    name: "Mechanical Keyboard RGB",
    description:
      "Premium mechanical keyboard with customizable RGB lighting and hot-swappable switches. Elevate your typing experience.",
    price: 169.99,
    originalPrice: 199.99,
    images: [
      "/mechanical-keyboard-rgb-black-premium.jpg",
      "/keyboard-rgb-lighting-dark.jpg",
      "/keyboard-desk-setup-lifestyle.jpg",
      "/keyboard-keycaps-detail.jpg",
    ],
    category: "gadgets",
    brand: "TECH STORE",
    features: ["Hot-Swappable", "RGB Per-Key", "Aluminum Frame", "PBT Keycaps"],
    variants: {
      colors: ["Space Black", "Silver White"],
    },
    stock: 80,
    rating: 4.8,
    reviews: 1423,
    isNew: false,
  },
  {
    id: 7,
    name: "Wireless Charging Pad",
    description:
      "Elegant wireless charger with fast charging support. Charge your devices effortlessly with premium design.",
    price: 79.99,
    originalPrice: 99.99,
    images: [
      "/wireless-charging-pad-black-minimal.jpg",
      "/charging-pad-with-phone.jpg",
      "/wireless-charger-desk-setup.jpg",
      "/charging-pad-led-indicator.jpg",
    ],
    category: "accessories",
    brand: "TECH STORE",
    features: ["15W Fast Charge", "Qi Compatible", "LED Indicator", "Anti-Slip Base"],
    variants: {
      colors: ["Onyx", "Pearl"],
    },
    stock: 150,
    rating: 4.5,
    reviews: 876,
    isNew: true,
  },
  {
    id: 8,
    name: "Smart Home Hub",
    description: "Central control for your smart home ecosystem. Voice-enabled with support for all major platforms.",
    price: 249.99,
    originalPrice: 299.99,
    images: [
      "/smart-home-hub-black-modern.jpg",
      "/smart-hub-display-interface.jpg",
      "/smart-hub-living-room-setup.jpg",
      "/smart-hub-side-profile.jpg",
    ],
    category: "gadgets",
    brand: "TECH STORE",
    features: ["Voice Control", "Multi-Platform", "Touch Display", "Mesh Network"],
    variants: {
      colors: ["Charcoal", "Light Gray"],
    },
    stock: 40,
    rating: 4.7,
    reviews: 654,
    isNew: false,
  },
]

export const collections = [
  {
    id: 1,
    name: "Smart Watches",
    slug: "watches",
    description: "Luxury timepieces for the modern era",
  },
  {
    id: 2,
    name: "Audio Elite",
    slug: "earbuds",
    description: "Premium sound experiences",
  },
  {
    id: 3,
    name: "Essential Gadgets",
    slug: "gadgets",
    description: "Must-have tech for everyday life",
  },
  {
    id: 4,
    name: "Power Accessories",
    slug: "accessories",
    description: "Power up your devices in style",
  },
]

export const categories = [
  { id: "all", name: "All Products" },
  { id: "earbuds", name: "Earbuds" },
  { id: "watches", name: "Watches" },
  { id: "headphones", name: "Headphones" },
  { id: "gadgets", name: "Gadgets" },
  { id: "accessories", name: "Accessories" },
]
